version: '3.7'

services:
  receiver:
    build: .
    ports:
      # I want this to be visible from the tag manager, so it needs to listen on the local network.
      - "0.0.0.0:8900:8900"
    volumes:
      - "./config/receiver:/var/receiver:rw"
    command:
      - "-influx"
      - "/var/receiver/config.json"

  db:
    image: "influxdb:2.0.4-alpine"
    volumes:
      - "influxdb:/var/lib/influxdb2"
    ports:
      - "127.0.0.1:8086:8086"

volumes:
  influxdb:
